// Module generated by generators/pwl_exp.py
module pwl_exp_lut(
    input  logic [4:0] segment_index,  // Log2(NUM_SEGMENTS)
    output logic signed [15:0] slope,
    output logic signed [15:0] intercept
);

    logic signed [15:0] slopes [31:0];
    logic signed [15:0] intercepts [31:0];

    initial begin
        slopes[0] = 0;
        intercepts[0] = 3;
        slopes[1] = 0;
        intercepts[1] = 6;
        slopes[2] = 1;
        intercepts[2] = 9;
        slopes[3] = 1;
        intercepts[3] = 14;
        slopes[4] = 3;
        intercepts[4] = 22;
        slopes[5] = 5;
        intercepts[5] = 34;
        slopes[6] = 8;
        intercepts[6] = 51;
        slopes[7] = 14;
        intercepts[7] = 77;
        slopes[8] = 24;
        intercepts[8] = 116;
        slopes[9] = 40;
        intercepts[9] = 171;
        slopes[10] = 66;
        intercepts[10] = 249;
        slopes[11] = 109;
        intercepts[11] = 356;
        slopes[12] = 179;
        intercepts[12] = 498;
        slopes[13] = 296;
        intercepts[13] = 673;
        slopes[14] = 488;
        intercepts[14] = 865;
        slopes[15] = 805;
        intercepts[15] = 1024;
        slopes[16] = 1328;
        intercepts[16] = 1024;
        slopes[17] = 2190;
        intercepts[17] = 593;
        slopes[18] = 3611;
        intercepts[18] = -827;
        slopes[19] = 5954;
        intercepts[19] = -4342;
        slopes[20] = 9816;
        intercepts[20] = -12067;
        slopes[21] = 16185;
        intercepts[21] = -27988;
        slopes[22] = 26685;
        intercepts[22] = -59488;
        slopes[23] = 43996;
        intercepts[23] = -120077;
        slopes[24] = 72538;
        intercepts[24] = -234243;
        slopes[25] = 119595;
        intercepts[25] = -446000;
        slopes[26] = 197178;
        intercepts[26] = -833919;
        slopes[27] = 325093;
        intercepts[27] = -1537447;
        slopes[28] = 535987;
        intercepts[28] = -2802816;
        slopes[29] = 883694;
        intercepts[29] = -5062910;
        slopes[30] = 1456966;
        intercepts[30] = -9075810;
        slopes[31] = 2402131;
        intercepts[31] = -16164547;
    end

    always_comb begin
        slope = slopes[segment_index];
        intercept = intercepts[segment_index];
    end

endmodule